"""London NHS trust reference data — ODS codes, names, postcodes, coordinates."""

LONDON_TRUSTS: dict[str, dict] = {
    "R1H": {
        "name": "Barts Health NHS Trust",
        "postcode": "E1 1FR",
        "lat": 51.5181,
        "lng": -0.0590,
    },
    "R1K": {
        "name": "London North West University Healthcare NHS Trust",
        "postcode": "HA1 3UJ",
        "lat": 51.5790,
        "lng": -0.3187,
    },
    "RAL": {
        "name": "Royal Free London NHS Foundation Trust",
        "postcode": "NW3 2QG",
        "lat": 51.5535,
        "lng": -0.1654,
    },
    "RAN": {
        "name": "Royal National Orthopaedic Hospital NHS Trust",
        "postcode": "HA7 4LP",
        "lat": 51.6311,
        "lng": -0.3125,
    },
    "RAS": {
        "name": "The Hillingdon Hospitals NHS Foundation Trust",
        "postcode": "UB8 3NN",
        "lat": 51.5340,
        "lng": -0.4739,
    },
    "RAX": {
        "name": "Kingston and Richmond NHS Foundation Trust",
        "postcode": "KT2 7QB",
        "lat": 51.4145,
        "lng": -0.2863,
    },
    "RF4": {
        "name": "Barking, Havering and Redbridge University Hospitals NHS Trust",
        "postcode": "RM7 0AG",
        "lat": 51.5759,
        "lng": 0.1601,
    },
    "RJ1": {
        "name": "Guy's and St Thomas' NHS Foundation Trust",
        "postcode": "SE1 7EH",
        "lat": 51.4987,
        "lng": -0.1176,
    },
    "RJ2": {
        "name": "Lewisham and Greenwich NHS Trust",
        "postcode": "SE13 6LH",
        "lat": 51.4546,
        "lng": -0.0138,
    },
    "RJ6": {
        "name": "Croydon Health Services NHS Trust",
        "postcode": "CR7 7YE",
        "lat": 51.3869,
        "lng": -0.1108,
    },
    "RJ7": {
        "name": "St George's University Hospitals NHS Foundation Trust",
        "postcode": "SW17 0QT",
        "lat": 51.4272,
        "lng": -0.1744,
    },
    "RJZ": {
        "name": "King's College Hospital NHS Foundation Trust",
        "postcode": "SE5 9RS",
        "lat": 51.4683,
        "lng": -0.0937,
    },
    "RKE": {
        "name": "Whittington Health NHS Trust",
        "postcode": "N19 5NF",
        "lat": 51.5656,
        "lng": -0.1383,
    },
    "RP4": {
        "name": "Great Ormond Street Hospital for Children NHS Foundation Trust",
        "postcode": "WC1N 3JH",
        "lat": 51.5228,
        "lng": -0.1200,
    },
    "RP6": {
        "name": "Moorfields Eye Hospital NHS Foundation Trust",
        "postcode": "EC1V 2PD",
        "lat": 51.5271,
        "lng": -0.0886,
    },
    "RPY": {
        "name": "The Royal Marsden NHS Foundation Trust",
        "postcode": "SW3 6JJ",
        "lat": 51.4893,
        "lng": -0.1683,
    },
    "RQM": {
        "name": "Chelsea and Westminster Hospital NHS Foundation Trust",
        "postcode": "SW10 9NH",
        "lat": 51.4846,
        "lng": -0.1818,
    },
    "RQX": {
        "name": "Homerton Healthcare NHS Foundation Trust",
        "postcode": "E9 6SR",
        "lat": 51.5474,
        "lng": -0.0434,
    },
    "RRV": {
        "name": "University College London Hospitals NHS Foundation Trust",
        "postcode": "NW1 2BU",
        "lat": 51.5247,
        "lng": -0.1368,
    },
    "RVR": {
        "name": "Epsom and St Helier University Hospitals NHS Trust",
        "postcode": "SM5 1AA",
        "lat": 51.3756,
        "lng": -0.1989,
    },
    "RYJ": {
        "name": "Imperial College Healthcare NHS Trust",
        "postcode": "W2 1NY",
        "lat": 51.5170,
        "lng": -0.1740,
    },
    "NDA": {
        "name": "HCRG Care Services Ltd",
        "postcode": "BA1 1HA",
        "lat": 51.3807,
        "lng": -2.3590,
    },
    "NT3": {
        "name": "Spire Healthcare",
        "postcode": "WC1V 6HX",
        "lat": 51.5194,
        "lng": -0.1109,
    },
}

# ODS codes used for filtering NHS CSV data
LONDON_ODS_CODES: set[str] = set(LONDON_TRUSTS.keys())

# Cancer types by standard (as they appear in the CSV)
CANCER_TYPES_FDS = [
    "Suspected acute leukaemia",
    "Suspected brain/central nervous system tumours",
    "Suspected breast cancer",
    "Suspected cancer - non-specific symptoms",
    "Suspected children's cancer",
    "Suspected gynaecological cancer",
    "Suspected haematological malignancies (excluding acute leukaemia)",
    "Suspected head & neck cancer",
    "Suspected lower gastrointestinal cancer",
    "Suspected lung cancer",
    "Suspected other cancer",
    "Suspected sarcoma",
    "Suspected skin cancer",
    "Suspected testicular cancer",
    "Suspected upper gastrointestinal cancer",
    "Suspected urological malignancies (excluding testicular)",
]

CANCER_TYPES_31D_62D = [
    "Breast",
    "Gynaecological",
    "Haematological - Lymphoma",
    "Haematological - Other (a)",
    "Head & Neck",
    "Lower Gastrointestinal",
    "Lung",
    "Other (a)",
    "Skin",
    "Upper Gastrointestinal - Hepatobiliary",
    "Upper Gastrointestinal - Oesophagus & Stomach",
    "Urological - Other (a)",
    "Urological - Prostate",
]

# Simplified display names mapping cancer types to a common key
CANCER_TYPE_DISPLAY = {
    "Suspected breast cancer": "Breast",
    "Suspected gynaecological cancer": "Gynaecological",
    "Suspected head & neck cancer": "Head & Neck",
    "Suspected lower gastrointestinal cancer": "Lower GI",
    "Suspected lung cancer": "Lung",
    "Suspected skin cancer": "Skin",
    "Suspected upper gastrointestinal cancer": "Upper GI",
    "Suspected urological malignancies (excluding testicular)": "Urological",
    "Suspected testicular cancer": "Testicular",
    "Suspected sarcoma": "Sarcoma",
    "Suspected haematological malignancies (excluding acute leukaemia)": "Haematological",
    "Suspected brain/central nervous system tumours": "Brain/CNS",
    "Suspected acute leukaemia": "Acute Leukaemia",
    "Suspected children's cancer": "Children's Cancer",
    "Suspected cancer - non-specific symptoms": "Non-specific",
    "Suspected other cancer": "Other",
    "Breast": "Breast",
    "Gynaecological": "Gynaecological",
    "Head & Neck": "Head & Neck",
    "Lower Gastrointestinal": "Lower GI",
    "Lung": "Lung",
    "Skin": "Skin",
    "Upper Gastrointestinal - Hepatobiliary": "Upper GI (Hepatobiliary)",
    "Upper Gastrointestinal - Oesophagus & Stomach": "Upper GI (Oesophagus & Stomach)",
    "Urological - Other (a)": "Urological (Other)",
    "Urological - Prostate": "Urological (Prostate)",
    "Haematological - Lymphoma": "Haematological (Lymphoma)",
    "Haematological - Other (a)": "Haematological (Other)",
    "Other (a)": "Other",
}
